/* ADDA Slough — shared site data + search. Loaded by SiteHeader and Search pages. */
(function () {
  const M = 'https://media.adda-slough.org/public/images/'; // Adda media server (live source). Local assets live under assets/images/.
  const P = { home: 'Home.dc.html', about: 'About.dc.html', events: 'Events.dc.html', reg: 'Registration.dc.html', fest: 'Festivals.dc.html', cult: 'Cultural.dc.html', sport: 'Sports.dc.html', charity: 'Charity.dc.html', a22: 'AddaAid2022.dc.html', a21: 'AddaAid2021.dc.html', a20: 'AddaAid2020.dc.html', media: 'Media.dc.html', print: 'Print.dc.html', digital: 'Digital.dc.html', contact: 'Contact.dc.html', signin: 'SignIn.dc.html', terms: 'Terms.dc.html', privacy: 'Privacy.dc.html', search: 'Search.dc.html' };

  const NAV = [['home', 'Home', P.home], ['about', 'About', P.about], ['events', 'Events', P.events], ['charity', 'Charity', P.charity], ['media', 'Media', P.media], ['contact', 'Contact', P.contact]];

  const FAMILY = [['amf001.jpg', 'Neel, Oindrila, Oviyan & Nimisha'], ['amf002.jpg', 'Prady & Indrani'], ['amf003.jpg', 'Prasenjit & Esha'], ['amf004.jpg', 'Debraj, Chaitali & Reyansh'], ['amf005.jpg', 'Anumita, Tojo & Eshana'], ['amf006.jpg', 'Kiaan, Kiyara, Lahori & Samrat'], ['amf007.jpg', 'Abhishek, Ridhaana & Ritwika'], ['amf008.jpg', 'Deeptanal, Debarati & Devadyuti'], ['amf009.jpg', 'Aritra, Mitul, Anmesh & Anumegha'], ['amf010.jpg', 'Arun, Chameli, Anvita & Anika'], ['amf012.jpg', 'Lisa, Leoan, Monideepa & Utpal'], ['amf013.jpg', 'Arijeet, Bandana & Arunava'], ['amf014.jpg', 'Dhiraj & Noopur'], ['amf015.jpg', 'Abhijit Ayetri & Ananya'], ['amf016.png', 'Sudipta & Suhasini'], ['amf017.png', 'Sandip, Ishita & Vivaan'], ['amf018.jpg', 'Aparajita, Raman, Abhinav & Nayontara'], ['amf019.jpg', 'Suvrasis & Juri'], ['amf020.png', 'Sandip, Monica, Ivy & Adi'], ['amf022.jpg', 'Ishita & Saikat'], ['amf023.jpg', 'Souvik, Malini & Arjun'], ['amf024.jpg', 'Archan, Nabanita & Ayush'], ['amf031.jpg', 'Abhishek Roy'], ['amf032.jpg', 'Paromita, Sourav & Parav'], ['amf033.jpg', 'Sandipan, Ria & Risan'], ['amf034.jpg', 'Munmun, Byomkesh, Koyna & Akshita'], ['amf035.jpg', 'Debalok, Saonli & Diwisha'], ['amf036.jpg', 'Poulami, Virat, Vanshika & Vamika'], ['amf037.jpg', 'VaniShree, Rajamarthandan & Dakshayani'], ['amf038.jpg', 'Arindam, Anushreya, Anahi & Ayra'], ['amf039.jpg', 'Sauvik & Tanisha'], ['amf040.jpg', 'Siddhartha, Pritha & Divisha'], ['apf001.png', 'Abhisek, Ishan & Jessica'], ['apf002.jpg', 'Rupali, Indranil & Ayushman']].map(([f, names]) => ({ img: M + 'org/people/' + f, names }));

  const PROGRAMMES = [['Solo/Group Performance', 'Cultural programme'], ['Antakshari', 'Gaata Rahe Mera Dil'], ['Bollywood Quiz', 'Puchho Zara Puchho'], ['Little Champ', 'Taare Zameen Par'], ['Sit & Draw', 'Satrangi Re'], ['Sharod Shriman & Shrimati', 'Competition'], ['Brain Teaser', 'Bheja Fry']];


  const E = M + 'events/';
  const ev = (base, list) => list.map(([id, title]) => ({ id, title, img: E + base + id + '.jpg' }));
  const ARCH = {
    festivals: { key: 'festivals', title: 'Festivals', href: P.fest, intro: 'Homely and attractive Pujo celebrations upholding Bengal’s tradition and culture in the UK.', subs: [
      { id: 'durga-pujo', title: 'Durga Pujo', img: E + 'festivals/durga-pujo/durga-pujo-2023.jpg', text: [
        'The Durga Puja festival holds immense emotional significance for Bengalis and Indians worldwide, recently acknowledged as a UNESCO World Heritage Festival. In Slough, the organization Adda achieved considerable success by orchestrating the Kali Puja since 2014. Building on this achievement, Adda, with the collective efforts of its members, initiated the inaugural Durga Puja in 2019.',
        'Distinguished for its unique presentation, featuring a Bengal-style pandal in an open ground and a central theme of ‘adda’ (chitchat) adjacent to the pandal at Maddox Square on the premises of Slough Cricket Club, the event resonated remarkably well with devotees. The ambiance and offerings, including authentic Indian food available for purchase, created an environment that transported attendees from London to the heart of Kolkata. The event’s success was further solidified when Adda received the esteemed “Best Durga Puja in UK 2019” award.',
        'In 2020, during the COVID-19 pandemic and the subsequent UK lockdown, Adda took a unique initiative to positively impact the mental well-being of the population. Understanding the significance of the auspicious day of Maha Ashtami during the Durga Puja, Adda organized an online pushpanjali over Zoom. This innovative approach garnered significant attendance and received highly encouraging feedback via social media channels. Despite the prevailing grief and sadness, people felt a sense of positivity through this initiative.',
        'Moving into 2021, with permissions granted for large-scale events, Adda, as a recognized charitable organization, remained committed to its societal responsibilities. Acknowledging the immense impact of the COVID pandemic on lives and livelihoods, Adda themed its Durga Puja as the “Gate of Joy,” inspired by Kolkata’s reputation as the “City of Joy.” Moreover, to enhance the Bengali cultural experience during the festival, Adda hosted live cooking sessions on-site with vendors from Kolkata, India, and Dhaka, Bangladesh. This initiative aimed not only to elevate the “Bengali” essence during the event but also served as a humble effort to foster a bond between the two Bengals transcending borders. The event witnessed an average daily footfall of around 3000-4000 people, accumulating an overall attendance of approximately 12,000 individuals throughout the festival.',
        'In our continuous pursuit of enhancement and uniqueness, Adda aims to make 2022 an exceptionally special year. The idols for this year’s celebration have been sourced from West Bengal and are the largest in size among all the celebrations throughout the UK. Devotees can expect a magnificent spectacle and an extraordinary experience.'
      ], events: ev('festivals/durga-pujo/', [['durga-pujo-2025', 'Durga Pujo 2025'], ['durga-pujo-2024', 'Durga Pujo 2024'], ['durga-pujo-2023', 'Durga Pujo 2023'], ['durga-pujo-2022', 'Durga Pujo 2022'], ['durga-pujo-2021', 'Durga Pujo 2021'], ['durga-pujo-2019', 'Durga Pujo 2019']]) },
      { id: 'kali-pujo', title: 'Kali Pujo', img: E + 'festivals/kali-pujo/kali-pujo-2024.jpg', text: [], events: ev('festivals/kali-pujo/', [['kali-pujo-2025', 'Kali Pujo 2025'], ['kali-pujo-2024', 'Kali Pujo 2024'], ['kali-pujo-2023', 'Kali Pujo 2023'], ['kali-pujo-2022', 'Kali Pujo 2022'], ['kali-pujo-2021', 'Kali Pujo 2021'], ['kali-pujo-2019', 'Kali Pujo 2019']]) },
      { id: 'saraswati-pujo', title: 'Saraswati Pujo', img: E + 'festivals/saraswati-pujo/saraswati-pujo-2025.jpg', text: [
        'Devi Saraswati holds a revered place in Hindu beliefs, symbolizing knowledge, wisdom, art, culture, speech, and learning. Her significance dates back to the Vedic period, with the earliest mention found in the Rigveda, a sacred Hindu scripture. Saraswati Puja, dedicated to Devi Saraswati, is celebrated on Basanta Panchami, which marks the onset of the spring season (Basanta Kaal).',
        'During Saraswati Puja, devotees pay homage to Goddess Saraswati, seeking her blessings for wisdom, intellect, creativity, and learning. It’s a vibrant and colorful celebration observed with devotion, often involving prayers, offerings, cultural events, and educational activities. Students often seek her blessings for academic success, and artists and scholars honour her for inspiration and creativity. The festival signifies the onset of spring, symbolizing new beginnings and the blossoming of knowledge and arts.',
        'Adda has been organising Saraswati Puja since 2013, fostering a tradition of worship with unwavering faith and splendor. Throughout the years, the puja venue has transitioned from the Copthorne Hotel banquet hall to the Singh Sabha Sports Centre and currently at the Slough Hindu Temple in Cippenham. Each year, the event maintains a consistent schedule comprising Saraswati Puja, Pushpanjali (offering of flowers), Hathey Khori (children’s initiation into education), cultural performances, and a vegetarian lunch.',
        'Special emphasis is placed on cultural programs cantered around children’s performances, aiming to transmit Hindu traditions to the next generation. The intent is to foster a connection to their cultural roots. Additionally, select stalls are provided an opportunity to showcase their products, adding diversity to the puja experience.',
        'Over the years, the popularity of Adda’s Saraswati Puja has soared, witnessing a growing number of attendees annually. The event has garnered significant attention, drawing in around 1000 guests within a span of 6 to 8 hours. Adda remains committed to furthering the Saraswati Puja, aspiring to make it larger and more enriching each year, with the continued support and participation of its guests.'
      ], events: ev('festivals/saraswati-pujo/', [['saraswati-pujo-2026', 'Saraswati Pujo 2026'], ['saraswati-pujo-2025', 'Saraswati Pujo 2025'], ['saraswati-pujo-2024', 'Saraswati Pujo 2024'], ['saraswati-pujo-2023', 'Saraswati Pujo 2023'], ['saraswati-pujo-2022', 'Saraswati Pujo 2022'], ['saraswati-pujo-2020', 'Saraswati Pujo 2020']]) }
    ] },
    cultural: { key: 'cultural', title: 'Cultural & Other', href: P.cult, intro: 'Concerts, shows and community gatherings, for friends and for the whole community.', subs: [
      { id: 'cultural', title: 'Cultural', img: E + 'cultural-and-other/cultural/madhubanti-bagchi-2026.jpg', text: [], events: ev('cultural-and-other/cultural/', [['lagnajita-chakraborty-live-2025', 'Lagnajita Chakraborty Live 2025'], ['bangla-nababarsho-and-jojo-mukherjee-concert', 'Bangla Nababarsho & Jojo Mukherjee Concert'], ['somlata-and-the-aces-2024', 'Somlata & The Aces 2024'], ['bengali-nababarsho-2024', 'Bengali Nababarsho 2024'], ['bijoyar-adda-with-anupam-2023', 'Bijoyar Adda with Anupam 2023'], ['bengali-new-year-2023', 'Bengali New Year 2023'], ['adda-bijoya-concert-2022', 'Adda Bijoya Concert 2022'], ['10th-year-celebration-of-adda', '10th Year Celebration of Adda'], ['adda-musical-night-2022', 'Adda Musical Night 2022'], ['grand-bijoya-2021-stereo-nation', 'Grand Bijoya 2021 Stereo Nation'], ['2021-cactus-live-(virtual)-bengali-new-year-celebrations', '2021 Cactus Live (Virtual) Bengali New Year Celebrations'], ['zubeen-garg-concert-(bijoya-2019)', 'Zubeen Garg Concert (Bijoya 2019)']]) },
      { id: 'other', title: 'Other', img: E + 'cultural-and-other.jpg', text: [], events: ev('cultural-and-other/other/', [['holi-2026', 'Holi 2026'], ['holi-2025', 'Holi 2025'], ['adda-summer-picnic-2024', 'Adda Summer Picnic 2024'], ['holi-2024', 'Holi 2024'], ['adda-summer-picnic-2023', 'Adda Summer Picnic 2023'], ['holi-2023', 'Holi 2023'], ['adda-milan-mela-2022', 'Adda Milan Mela 2022'], ['holi-2022', 'Holi 2022']]) }
    ] },
    sports: { key: 'sports', title: 'Sports & Leisure', href: P.sport, intro: 'Promoting sports by organising Cricket, Football and Badminton tournaments.', subs: [
      { id: 'badminton-and-table-tennis', title: 'Badminton & Table Tennis', img: E + 'sports-and-leisure/badminton-and-table-tennis.jpg', text: [], events: ev('sports-and-leisure/badminton-and-table-tennis/', [['adda-badminton-and-table-tennis-2026', 'Adda Badminton & Table Tennis 2026'], ['adda-badminton-and-table-tennis-2025', 'Adda Badminton & Table Tennis 2025'], ['adda-badminton-and-table-tennis-2024', 'Adda Badminton & Table Tennis 2024'], ['adda-badminton-and-table-tennis-2023', 'Adda Badminton & Table Tennis 2023'], ['adda-vs-mkac-badminton-2022-(away-match)', 'Adda vs MKAC Badminton 2022 (Away Match)'], ['adda-badminton-2022', 'Adda Badminton 2022'], ['adda-vs-mkac-badminton-2022-(home-match)', 'Adda vs MKAC Badminton 2022 (Home Match)']]) },
      { id: 'cricket', title: 'Cricket', img: E + 'sports-and-leisure/cricket.jpg', text: [], events: ev('sports-and-leisure/cricket/', [['adda-cricket-2026', 'Adda Cricket 2026'], ['gbs-adda-cricket-2025', 'GBS Adda Cricket 2025'], ['adda-cricket-2024', 'Adda Cricket 2024'], ['adda-cricket-2023', 'Adda Cricket 2023'], ["saurav-ganguly's-birthday-celebration-2022", "Saurav Ganguly's Birthday Celebration 2022"], ['adda-cricket-2022', 'Adda Cricket 2022']]) },
      { id: 'football', title: 'Football', img: E + 'sports-and-leisure/football.jpg', text: [], events: ev('sports-and-leisure/football/', [['adda-football-2022', 'Adda Football 2022']]) }
    ] }
  };
  const YEAR_NOTES = { 'durga-pujo-2019': 'Adda’s inaugural Durga Puja: a Bengal-style pandal in an open ground at Slough Cricket Club, with the ‘adda’ theme at Maddox Square. Winner of “Best Durga Puja in UK 2019”.', 'durga-pujo-2021': 'Themed “Gate of Joy”, with live cooking from vendors from Kolkata and Dhaka, and around 12,000 visitors across the festival.', 'durga-pujo-2022': 'Idols sourced from West Bengal, the largest in size among all the celebrations throughout the UK.' };
  // Full write-ups from the live event pages (adda-slough.org/events/<cat>/<sub>/<id>), word for word.
  const EVENT_TEXT = {
    'durga-pujo-2025': { date: '25–29 September 2025', text: [
      'ADDA celebrated its 7th Durga Pujo between September 25th to 29th, 2025. ADDA’s Durga Puja stands out as the first event in the UK to have a Kolkata-like Pandal since 2019, making it a significant and unique celebration within the Bengali community in the UK.',
      'The event have been a remarkable success, establishing itself as one of the largest Bengali Durga Pujo events in the UK. It offered plenty of open spaces and fun activities for everyone involved, fostering an inclusive and engaging atmosphere for attendees of all ages. This vibrant and culturally enriching event, celebrated with grandeur focus on preserving Bengali traditions while fostering community engagement.',
      '## Highlights of Adda Durga Pujo:',
      'ADDA’s Durga Pujo is acknowledged as the first in the UK to recreate a Kolkata-like Pandal, providing an authentic experience reminiscent of the traditional celebrations. The event aims to bring the Kolkata Pujo culture to the UK.',
      'The Pujo spans over four days and attracts a large audience, with over 18,000 attendees. It features various elements such as food stalls, cultural evenings, talent shows, and performances by folk singers, showcasing Bengal’s rich cultural heritage.',
      'ADDA is known for its exquisite Pandal interior decorations, representing mini-India. This year, it includes fine art paintings, craft displays from West Bengal, and the showcasing of artists Rama Bhowmik and Satabdi Saha’s work.',
      'An exceptional feature this year is the lighting display from Chandannagar, the first of its kind in Europe, which has generated considerable interest and discussion.',
      'The event’s food court offers a diverse range of mouth-watering Bengali and Indian delicacies, including Kolkata street food, comfort foods, and specialties from both West Bengal and East Bengal, fostering a cultural amalgamation.',
      'There is a focus on involving children in cultural activities and creating an engaging environment for them. In previous years, activities like sit and draw competitions, talent showcases, and this year, introducing a marshal arts demonstration for young kids aimed at making the Pujo memorable and enjoyable for the younger audience.',
      'Through initiatives like showcasing art and artifacts from West Bengal, Chandannagar lighting displays, and arranging funfair rides resembling Indian village fairs, ADDA aims to pass on cultural heritage to younger generations and create a bridge between two Bengals.'
    ] }
  };
  EVENT_TEXT['durga-pujo-2024'] = { date: '10–13 October 2024', text: ['ADDA celebrated its 6th Durga Pujo between October 10th and 13th, 2024. ADDA’s Durga Puja stands out as the first event in the UK to have a Kolkata-like Pandal since 2019, making it a significant and unique celebration within the Bengali community in the UK.', ...EVENT_TEXT['durga-pujo-2025'].text.slice(1)] };
  { const b = EVENT_TEXT['durga-pujo-2025'].text; EVENT_TEXT['durga-pujo-2023'] = { date: '20–23 October 2023', text: ['ADDA’s celebrated its 5th Durga Pujo between October 20th and 23rd, 2023. ADDA’s Durga Puja stands out as the first event in the UK to have a Kolkata-like Pandal since 2019, making it a significant and unique celebration within the Bengali community in the UK.', b[1], b[2], b[3], b[4].replace('over 18,000 attendees', 'over 15,000 attendees'), b[5], b[6], b[7], 'There is a focus on involving children in cultural activities and creating an engaging environment for them. In previous years, activities like sit and draw competitions, talent showcases, and this year, introducing a funfair with rides like bumper cars, ferris wheels, and carousels, aimed at making the Pujo memorable and enjoyable for the younger audience.', b[9]] }; }
  EVENT_TEXT['holi-2026'] = { text: ['For over a decade, Adda Slough had been a beacon for the Indian diaspora, fostering connection through vibrant festivals, sports, and charitable work. This year’s Holi celebration was no exception—an opulent and joyous event that embodied unity and diversity.', 'Set against the stunning backdrop of England\'s green pastures, families from all across the UK came together to create one big Indian family gathering. With non-toxic colors and a spirit of togetherness, we brought a slice of "home away from home" to everyone who joined in. It was more than a festival; it was a celebration of belonging. Memories were made as vivid as the colors of Holi!'] };
  EVENT_TEXT['adda-cricket-2026'] = { text: ['Adda Cricket tournament leads into its 12th year! Fifteen teams will celebrate the occasion with Adda by not only watching but also playing in a competitive Adda Cricket Tournament 2026. Much like the World Cup, the tournament was full of twists and turns, with many teams that have consistently performed well over the last eleven years not making it past the group and league stages.'] };
  EVENT_TEXT['durga-pujo-2022'] = { text: ["Adda successfully celebrated its 4th Durga Pujo, establishing itself as one of the largest Bengali Durga Pujo events in the UK. The event have been a vibrant embodying the essence of Kolkata’s Pujo culture while catering to a diverse audience.","## Highlights :","The event attracted close to 15000 attendees over four days, showcasing its popularity and ability to engage a significant number of people within the Indian and Bengali community.","The celebration featured a big pandal, numerous food stalls offering diverse Bengali cuisine, and cultural evenings. These elements likely contributed to creating an immersive experience reminiscent of traditional Durga Pujo celebrations in Kolkata.","Adda provided a platform for local talents, including folk singers and kids’ talent shows. This not only entertained the attendees but also promoted and nurtured local talent within the community.","The presence of stalls from Bengal, offering authentic merchandise or products, likely contributed to the event’s authentic cultural representation and provided attendees with a taste of home.","The event appears to have encapsulated tradition, fun, and the essence of Adda (chitchat or conversations), fostering a strong sense of community and togetherness among attendees.","Adda Durga Pujo play a crucial role in preserving cultural heritage, fostering a sense of belonging within the diaspora, and creating spaces for cultural exchange and celebration. Adda’s successful event seems to have encapsulated these aspects, providing an enriching and memorable experience for all the attendees."] };
  EVENT_TEXT['durga-pujo-2021'] = { text: ["UNESCO recognizing Durga Puja as a world heritage festival is a testament to its cultural richness, diversity, and the way it brings communities together in celebration and devotion. The emotional bond that Bengalis and Indians share with Durga Puja transcends geographical boundaries, connecting people through shared traditions, values, and festivities, no matter where they are in the world.","To uphold the community spirit and preserve cultural heritage within diasporic communities Adda started Durga Pujo in 2019. However, due to the challenges posed by the COVID-19 pandemic, there was a gap in the celebrations in 2020, as many events and gatherings worldwide were either postponed or cancelled to ensure public safety and adhere to health guidelines. Resuming the Durga Pujo celebration again in 2021 despite the previous year’s hiatus demonstrates Adda’s commitment to fostering cultural connections and continuing the tradition of celebrating this significant festival.","The theme of Adda Durga Pujo 2021 was “Gate of Joy” inspired by Kolkata’s identity as the “City of Joy,”. Constructing the gate at the entrance of the puja pandal using small idols sourced from local artists in Purulia, West Bengal, not only added to the authenticity of the celebration but also provided support to artisans affected by the COVID-19 pandemic. This initiative not only helped them financially but also allowed them to participate in the joyous occasion of Durga Puja, even while residing far away in Slough, UK.","The inclusion of live cooking on-site by vendors from Kolkata, India, and Dhaka, Bangladesh, aimed at enriching the Bengali flavour of the festival while also fostering cultural bonds between the two Bengals. Such efforts not only showcase cultural richness but also bridge geographical boundaries, promoting unity and harmony beyond borders.","Adda Durga Pujo’s success is evident from the significant footfall, averaging around 3000-4000 attendees daily, resulting in an overall attendance of 12,000 over the course of the celebration. This level of attendance reflects the event’s popularity, impact, and ability to engage and attract a diverse audience, further strengthening the celebration’s cultural significance and community involvement."] };
  EVENT_TEXT['durga-pujo-2019'] = { text: ["To uphold the community spirit and preserve cultural heritage within diasporic communities Adda started Durga Pujo in 2019.","Adda’s effort was recognised by national and international media who coveted and branded us as “Maddox Square” of London. It is for organising the event in a Bengal-style pandal in an open ground, with the central theme of “adda” (chitchat) which proved to be highly appealing to devotees. This setting, along with authentic Indian food available for purchase, created an immersive experience reminiscent of celebrations in Kolkata.","Adda was awarded the “Best Durga Puja in UK 2019”! It’s truly an honour and a testament to the dedication, effort, and cultural significance of Adda’s celebration of Durga Pujo. Receiving such an esteemed award not only acknowledges the hard work and commitment of the members and patrons but also highlights the event’s success in bringing the essence of Durga Pujo to the UK. This recognition adds a significant feather to Adda’s cap and underscores its position as a leader in organizing and preserving cultural traditions within the diasporic community. It’s a moment of pride and accomplishment for Adda and its members, affirming the success and impact of our efforts in celebrating Durga Pujo in the UK."] };
  EVENT_TEXT['holi-2025'] = { text: EVENT_TEXT['holi-2026'].text };
  EVENT_TEXT['adda-summer-picnic-2024'] = { text: ['Here are a few glimpses of Adda  Picnic 2024. Thank you all for the support. The event was filled with fun activities and prizes.  Food partner for this event was Party Pals ... Special thanks to Malobika Roy , food was appreciated by everyone.'] };
  EVENT_TEXT['holi-2024'] = { text: ["One of the fun filled events with lots of colours, keeping to the tradition of a spring get together. Hosting our guests with colours, food, fashion and various entertainment. Adda celebrated Holi 2024 at 3rd Upton Scout Hall, Slough for all the people of all age groups to have a fun filled colourfull event."] };
  EVENT_TEXT['adda-milan-mela-2022'] = { text: ["Adda Milan Mela and Fun Day organised by Ladies of Adda at Wexham Parish Hall on 16th July 2022.","There were about 20 stalls displaying their products:","⚡️SAREES AND LEHENGAS 👗","⚡️Jeweleries filtered and glamorised the venue","Unique hand crafted earrings, necklaces and many more 💍🌟","⚡️Chat, Phuckas and Biriyanis reminding the mouthwatering street food of India 😋 👅 and probably our favorite Biriyani place SHIRAZ…….Who could forget that famous Biriyani and Rezala and we were lucky to get that here in UK 😋😋on 🗓 July 16 at Wexham Parish Hall, Norway Drive, Slough, SL2 5QP 😄😄","Aritra Bhattacharya"] };
  EVENT_TEXT['gbs-adda-cricket-2025'] = { text: ["## Heartfelt Thanks:","To the 15 teams, dedicated volunteers, match officials, Councillor Neel Rana, and our valued sponsor GBS for making this year's tournament a resounding success! Your support was invaluable, and we're thrilled to announce:","- Champions:Slough Rockers","- Runners-up:AZAD Club","With Captain David at the helm, the Slough Rockers have made history by winning the cup an impressive three times in 12 years – a feat unmatched by any other team, with most teams managing just one win.","Thank you for being part of another memorable event for Adda!","Global Banking School UK's most respected institutions with  campuses in four of the UK’s biggest and most exciting cities – London, Manchester, Birmingham and Leeds. Wherever you study, you will have access to the same range of state-of-the-art facilities and top-quality teaching. For more info visit: https://www.globalbanking.ac.uk"] };
  EVENT_TEXT['adda-summer-picnic-2023'] = { date: '24 June 2023', text: ["On Saturday, 24th of June 2023 Adda organised Summar Picnic at Langley Country Park. It was a fun-filled outdoor picnic in Langley Park! The event was attended by 65 people to all with mouth-watering dishes, various games, and activities for everyone to enjoy. It was be a great opportunity to relax and catch up with friends and family while enjoying the beauty of nature and sunshine.Thanks to all participants for their continuous association with Adda. Hope you all had a great day","On behlaf of ADDA Summer Picnic Organizing Committee"] };
  const catPath = { festivals: 'festivals', cultural: 'cultural-and-other', sports: 'sports-and-leisure' };
  Object.values(ARCH).forEach(c => c.subs.forEach(s => s.events.forEach(e => { e.cat = c.key; e.catTitle = c.title; e.catHref = c.href; e.sub = s.id; e.subTitle = s.title; e.href = 'Event.dc.html?id=' + encodeURIComponent(e.id); e.note = YEAR_NOTES[e.id] || ''; const t = EVENT_TEXT[e.id] || {}; e.date = t.date || ''; e.text = t.text || []; e.gallery = t.gallery || []; e.live = 'https://adda-slough.org/events/' + catPath[c.key] + '/' + s.id + '/' + e.id; })));
  const ALL_EVENTS = Object.values(ARCH).flatMap(c => c.subs.flatMap(s => s.events));

  const I = (section, title, url, desc, kw) => ({ section, title, url, desc, kw: kw || '' });
  const INDEX = [
    I('Page', 'Home', P.home, 'Adda Slough: charitable trust organising charity, cultural and sports events in Slough.', 'welcome start main'),
    I('About', 'About Adda Slough', P.about, 'Our story since August 2012. Charity Registration Number 1183906.', 'history story charity number trust who we are'),
    I('About', 'Our mission', P.about + '#mission', 'Cultural integration, promoting sports and social responsibility.', 'aim goals values'),
    I('About', 'Adda Slough in numbers', P.about + '#metrics', '84 events and 9,200 followers.', 'metrics stats followers'),
    I('About', 'ADDA Family', P.about + '#family', 'The 34 families behind Adda Slough.', 'people team members committee volunteers trustees'),
    I('Events', 'Upcoming events', P.events, 'Durga Pujo 2026 and Madhubanti Bagchi live.', 'whats on calendar schedule dates'),
    I('Events', 'Durga Pujo 2026', P.events + '#durga-pujo', '16–20 October 2026 · Slough Cricket Club, Upton Court Road, SL3 7LT.', 'puja festival october pandal bhog prasad'),
    I('Events', 'Sponsor Bhog', P.events + '#bhog', 'Bhog + Puja + Meal £61 per family (max 2 adults & 2 kids).', 'donate offering prasad sponsor food meal'),
    I('Events', 'Madhubanti Bagchi 2026', P.events + '#madhubanti-bagchi', '31 October 2026, 18:00–22:00 · Hexagon, Reading.', 'concert music singer bollywood tickets live show aaj ki raat alrich'),
    I('Forms', 'Durga Pujo 2026 programme registration', P.reg, 'Register to perform or compete at Durga Pujo 2026.', 'register sign up form perform compete talent stage entry'),
    ...PROGRAMMES.map(([n, s]) => I('Forms', n + ' · ' + s, P.reg + '#programmes', 'Durga Pujo 2026 programme. Register online.', 'programme competition register')),
    I('Events', 'Satrangi Re: Sit & Draw 2026', P.reg + '#programmes', 'Drawing and colouring competition for young artists.', 'kids children art drawing colouring'),
    I('Events', 'Srimaan & Srimoti 2026', P.reg + '#programmes', 'Pujo personality titles celebrating style.', 'fashion style competition'),
    I('Events', 'Memory Game Competition', P.reg + '#programmes', 'Pujo te brain-ero ekto pujo hok! Test your memory this Durga Puja.', 'brain game quiz couples'),
    I('Past events', 'Festivals', P.fest, 'Durga Pujo, Kali Pujo and Saraswati Pujo through the years.', 'archive history puja pujo'),
    I('Past events', 'Durga Pujo archive', P.fest + '#durga-pujo', 'Past Durga Pujo celebrations.', 'puja durga'),
    I('Past events', 'Kali Pujo', P.fest + '#kali-pujo', 'Kali Pujo celebrations.', 'puja kali diwali'),
    I('Past events', 'Saraswati Pujo', P.fest + '#saraswati-pujo', 'Saraswati Pujo celebrations.', 'puja saraswati'),
    I('Past events', 'Cultural & Other', P.cult, 'Concerts, shows and community gatherings.', 'music concert culture'),
    I('Past events', 'Sports & Leisure', P.sport, 'Cricket, football, badminton and table tennis.', 'sport games tournament'),
    I('Past events', 'Cricket', P.sport + '#cricket', 'ADDA cricket tournaments.', 'sport tournament'),
    I('Past events', 'Football', P.sport + '#football', 'ADDA football tournaments.', 'sport soccer tournament'),
    I('Past events', 'Badminton & Table Tennis', P.sport + '#badminton-and-table-tennis', 'Badminton and table tennis tournaments.', 'sport tournament ping pong'),
    I('Charity', 'Adda Aid', P.charity, 'How Adda Slough gives back to the community.', 'charity donate help relief'),
    I('Charity', 'Covid-19 support in Slough', P.charity + '#covid', 'Food, essentials and medicines delivered with partners: 50,000 people reached.', 'coronavirus pandemic food bank mitra mandal sewa day thames valley police'),
    I('Charity', 'Cyclone Amphan relief', P.charity + '#amphan', 'Relief in the Sundarbans with Kolkata Mary Ward Social Centre.', 'sundarban bengal kmwsc flood'),
    I('Charity', 'College Street books appeal', P.charity + '#books', 'Helping reprint textbooks lost at Kolkata’s Boi Para.', 'boi para kolkata publishers'),
    I('Charity', 'Adda Aid 2022', P.a22, 'Adda Aid, 2022.', 'charity 2022'),
    I('Charity', 'Adda Aid 2021', P.a21, 'Adda Aid, 2021.', 'charity 2021'),
    I('Charity', 'Adda Aid 2020', P.a20, 'Covid-19 support and Cyclone Amphan relief, 2020.', 'charity 2020 covid amphan'),
    I('Media', 'Media coverage', P.media, 'ADDA in print and digital media.', 'news press coverage'),
    I('Media', 'Print coverage', P.print, 'Times of India, Anandabazar, Bangla Post, Asian Voice, Slough Observer.', 'newspaper press clipping'),
    I('Media', 'The Times of India · Sep 2025', P.print + '#times-of-india', 'Durga Puja celebrations unite Bengali diaspora in England.', 'toi newspaper'),
    I('Media', 'Anandabazar · May 2023', P.print + '#anandabazar', 'Feature on Pujo in London (Bengali).', 'bengali newspaper'),
    I('Media', 'Bangla Post', P.print + '#bangla-post', 'Coverage in 2019, 2021 and 2022.', 'newspaper'),
    I('Media', 'Asian Voice · Oct 2020', P.print + '#asian-voice', 'Print coverage of ADDA Slough.', 'newspaper'),
    I('Media', 'Digital coverage', P.digital, 'ABP News, Republic Bangla TV, S NEWZ and our YouTube channel.', 'tv video online youtube'),
    I('Media', 'YouTube channel', 'https://www.youtube.com/@addaslough5239', 'Watch ADDA videos on YouTube.', 'video watch'),
    I('Live', 'Adda Live', 'Live.dc.html', 'Watch Adda Slough events live and catch up on previous live streams.', 'live stream streaming watch online broadcast video recording'),
    I('Contact', 'Contact us', P.contact, '31 Finefield Walk, Slough SL1 2QR · addasloughinformation@gmail.com', 'email phone call address help enquiry'),
    I('Forms', 'Membership form', P.contact + '#membership', 'Become a member of Adda Slough.', 'join member volunteer'),
    I('Forms', 'Sponsorship form', P.contact + '#sponsorship', 'Sponsor an event or book a stall.', 'sponsor stall business advertise'),
    I('Forms', 'Enquiry form', P.contact + '#enquiry', 'Send us a question or message.', 'question message help'),
    I('Page', 'Sign in', P.signin, 'Member and registration sign-in.', 'login account password edit registration'),
    I('Page', 'Terms & Conditions', P.terms, 'Terms of use for adda-slough.org.', 'legal terms'),
    I('Page', 'Privacy Policy', P.privacy, 'How we handle your data.', 'legal data gdpr cookies'),
    ...ALL_EVENTS.map(e => I('Past events', e.title, e.href, e.subTitle + ' · ' + e.catTitle, e.note + ' archive photos')),
    I('Past events', 'Other events', P.cult + '#other', 'Holi, summer picnics and Milan Mela.', 'picnic gathering holi colours mela'),
    I('Media', 'ABP News video', P.digital + '#abp-news', 'Watch ABP News coverage of Adda Slough (August 2022).', 'video tv watch'),
    ...FAMILY.map(f => I('ADDA Family', f.names, P.about + '#family', 'Member of the ADDA Family.', 'family people'))
  ];

  const SYN = { pujo: ['puja', 'durga', 'kali', 'saraswati'], puja: ['pujo'], pooja: ['pujo', 'puja', 'durga'], poojo: ['pujo', 'durga'], puja2: [], durgapuja: ['durga', 'pujo'], durgapujo: ['durga', 'pujo'], durgapooja: ['durga', 'pujo'], kalipuja: ['kali'], saraswatipuja: ['saraswati'], bhogo: ['bhog'], prashad: ['prasad', 'bhog'], prasadam: ['bhog'], adda: ['about', 'home'], donate: ['charity', 'aid', 'sponsor', 'bhog'], donation: ['charity', 'aid'], give: ['charity', 'donate'], help: ['charity', 'contact', 'aid'], photo: ['family', 'media', 'print'], photos: ['family', 'media'], gallery: ['media', 'family', 'festivals'], picture: ['media', 'family'], video: ['youtube', 'digital'], watch: ['youtube', 'digital'], tv: ['digital'], news: ['media', 'press', 'print'], newspaper: ['print'], article: ['print', 'media'], call: ['phone', 'contact'], mail: ['email', 'contact'], join: ['membership', 'register'], signup: ['register', 'membership'], login: ['sign', 'signin'], music: ['concert', 'madhubanti', 'cultural'], song: ['madhubanti', 'antakshari'], sing: ['antakshari', 'performance'], dance: ['performance'], show: ['concert', 'cultural'], sport: ['cricket', 'football', 'badminton'], sports: ['cricket', 'football', 'badminton'], game: ['memory', 'quiz', 'sports'], kids: ['little', 'draw', 'children'], children: ['kids', 'draw', 'little'], child: ['kids', 'draw'], food: ['bhog', 'prasad', 'meal'], ticket: ['madhubanti', 'concert'], tickets: ['madhubanti', 'concert'], team: ['family', 'trustees'], people: ['family'], member: ['membership', 'family'], volunteer: ['membership', 'enquiry'], stall: ['sponsorship'], venue: ['address', 'cricket', 'hexagon'], directions: ['address', 'venue'], location: ['address'], covid: ['aid', '2020'], cyclone: ['amphan'], cookie: ['privacy'], cookies: ['privacy'], data: ['privacy'], legal: ['terms', 'privacy'], diwali: ['kali'], festival: ['festivals', 'pujo'], history: ['festivals', 'about', 'archive'], past: ['archive', 'festivals'] };

  const norm = s => String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[’'&]/g, ' ').replace(/[^a-z0-9\u0980-\u09ff]+/g, ' ').trim();
  const lev = (a, b) => { if (Math.abs(a.length - b.length) > 2) return 9; let p = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 1; i <= a.length; i++) { const c = [i]; for (let j = 1; j <= b.length; j++) c[j] = Math.min(p[j] + 1, c[j - 1] + 1, p[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1)); p = c; } return p[b.length]; };
  INDEX.forEach(it => { it._t = norm(it.title); it._tw = it._t.split(' '); it._k = norm(it.kw + ' ' + it.section); it._d = norm(it.desc); it._all = (it._t + ' ' + it._k + ' ' + it._d).split(' '); });

  function direct(it, t) {
    if (it._tw.some(w => w.startsWith(t))) return 10;
    if (it._t.includes(t)) return 7;
    if (it._k.split(' ').some(w => w.startsWith(t))) return 5;
    if (it._d.includes(t)) return 3;
    return 0;
  }
  function loose(it, t) {
    let s = 0;
    (SYN[t] || []).forEach(x => { const d = direct(it, x); if (d) s = Math.max(s, d * 0.5); });
    if (t.length >= 4) { const tol = t.length >= 5 ? 2 : 1; if (it._all.some(w => w.length >= 3 && lev(t, w.slice(0, t.length + 1)) <= tol || lev(t, w) <= tol)) s = Math.max(s, 2.5); }
    return s;
  }
  function search(q, limit) {
    const toks = norm(q).split(' ').filter(Boolean);
    if (!toks.length) return { q, exact: [], related: [] };
    const exact = [], related = [];
    INDEX.forEach(it => {
      let all = true, score = 0, any = 0;
      toks.forEach(t => { const d = direct(it, t); if (d) { score += d; any++; } else { all = false; const l = loose(it, t); if (l) { score += l; any++; } } });
      if (it.section === 'ADDA Family') score -= 1;
      if (all) exact.push({ it, score }); else if (any) related.push({ it, score: score * (any / toks.length) });
    });
    const out = a => a.sort((x, y) => y.score - x.score).slice(0, limit || 50).map(x => x.it);
    return { q, exact: out(exact), related: out(related) };
  }

  const remote = src => (window.ADDA_REMOTE ? window.ADDA_REMOTE(src) : '');
  window.ADDA = { M, P, NAV, FAMILY, PROGRAMMES, INDEX, search, ARCH, ALL_EVENTS, SPONSORS: [], remote };
  window.dispatchEvent(new Event('adda-ready'));
})();
